# Site settings
title: Zai
email: zaithottakath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I should put something here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zaithottakath@" # the base hostname & protocol for your site
generic_username: zaithottakath
linkedin_username: zthottakath
# Build settings
markdown: kramdown